### ISSUE TITLE
Updating Deps and Possible API Changes

### ISSUE THREAD

**Issue by sstadick** [petabi/petal-decomposition#22]
Hello!

I've been using a forked version `petal-decomposition` for some exploratory work and wanted to see if you were open to a PR with some updates / how you would like to see those updates.

The primary change would be make subtracting the mean from the input data either optional, or extracted entirely and run before passing input to any of the fit / transform methods. That would allow users to perform their own standardization / normalization before passing anything in. 

Additionally, I'd like to add a variant that can take ownership of the input, since the first step would no longer be normalizing it, to avoid having to immediately copy the whole input matrix.

The other set up of updates would be updating the deps to more recent versions of ndarray / linalg. On [my fork](https://github.com/sstadick/petal-decomposition/tree/update_deps) I have it working with ndarray 0.14. 

If you'd rather just see a PR with proposed changes in it, I can do that as well! I just wanted to know if you are open to the existing API changing, or whether I should work around it.

**Comment by msk** [comment]
Sounds excellent! Please create PRs.

**Comment by sstadick** [comment]
https://github.com/petabi/petal-decomposition/pull/23 <- update deps for ndarray 0.14
https://github.com/petabi/petal-decomposition/pull/24 <- changes to PCA 

More than happy to make any suggested changes :+1:

**Comment by msk** [comment]
> The primary change would be make subtracting the mean from the input data either optional, or extracted entirely and run before passing input to any of the fit / transform methods.

It seems #24 implements the latter approach.

If the goal is to avoid the overhead of centering when the input is already centered, the former would be a better approach because it would keep the common use case (automatic centering in `Pca::fit`) simple. We can add, say, `Pca::fit_with_centered`, to handle centered input.

However, if there are good use cases of applying PCA to data with a non-zero mean, #24 would be a more flexible solution at the cost of manual centering before calling `Pca::fit`.

So far, I have an impression that the majority of PCA applications require a zero-mean input to SVD, and thus prefer keeping API simple for such cases. Any counterexamples?

**Comment by sstadick** [comment]
By no means do I feel like I have enough expertise to demonstrate that more PCA applications don't require a zero-mean input. In my particular use case the input is normalized, and applying mean-centering on top of the normalization produces different results than the reference implementation ([Equation 1](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4827102/pdf/main.pdf)). 

I am totally okay with providing a `Pca::fit_with_centered` method and defer to you with regards to what the more common case in the wild is.

The only other counterpoint I'd offer is that, IMO, explicit is preferable to implicit, and requiring a user, one way or another, to explicitly opt in to mean-centering, is more idiomatic for a Rust library.

Mostly though, as long as there  is at least one way to `fit` without mean centering I'm happy and my use case is satisfied :+1:

**Comment by sstadick** [comment]
After further review, I see what you mean about `mean centering` be pretty standard. In the contexts I use PCA (bioinformatics) it's usually standardized inputs.

I went ahead and sketched out a minimal footprint change that is more in line with the first option of making mean-centering optional: https://github.com/petabi/petal-decomposition/pull/26. If you have any insights into fixing the typing issue mentioned in the PR, I'd love to hear it even if neither of these options works out.

**Comment by msk** [comment]
Resolved in 0.5.1.

**Comment by sstadick** [comment]
Thank you!
